stages:
  - build_and_push
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  REMOTE_HOST: 212.28.189.176
  REMOTE_USER: root
  SERVICE_NAME: app
  STACK_NAME: compress-app
  DOCKER_TLS_CERTDIR: ""

build_and_push:
  stage: build_and_push
  image: docker:20.10.24
  services:
    - name: docker:20.10.24-dind
      alias: docker
  tags:
    - frontend
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f Dockerfile.prod .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: alpine:latest
  tags:
    - frontend
  before_script:
    - apk add --no-cache openssh-client sshpass docker-cli
  script:
    - echo "Deploying to VPS via SSH..."
    - |
      sshpass -p "Arafat2413*#" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST <<EOF
        set -e
        cd /root/compress
        echo "Logging into registry on VPS..."
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

        echo "Updating image tag in docker-compose.yml..."
        sed -i "/app:/,/image:/ s|image:.*|image: $IMAGE_TAG|" docker-compose.prod.yml

        echo "Pulling latest image..."
        docker-compose -f docker-compose.prod.yml pull $SERVICE_NAME

        echo "Re-deploying updated service..."
        docker-compose -f docker-compose.prod.yml up -d $SERVICE_NAME
