version: "3.9"

services:
  safefoods-redis:
    image: redis:7
    container_name: safefoods-redis
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_PORT}"
    volumes:
      - safefoods-redis-data:/data
    networks:
      - safefoods-app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

  safefoods-mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - safefoods-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 3

  safefoods-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: safefoods-app-dev
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure:3
    env_file:
      - .env
    depends_on:
      safefoods-postgres:
        condition: service_healthy
      safefoods-redis:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    command: sh -c "pnpm install && pnpm run dev"
    networks:
      - safefoods-app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT}/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

  safefoods-postgres:
    image: postgres:15
    container_name: safefoods-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"
    volumes:
      - safefoods-pg-data:/var/lib/postgresql/data
    networks:
      - safefoods-app-network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
volumes:
  safefoods-pg-data:
    driver: local
  safefoods-redis-data:
    driver: local
networks:
  safefoods-app-network:
    driver: bridge
